import './globals.scss';
import { Inter } from 'next/font/google';
import Providers from './hooks/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<main className='flex flex-col gap-5 min-h-screen p-2 md:py-4 md:px-8 xl:py-8 xl:px-16'>
					<Providers>{children}</Providers>
				</main>
			</body>
		</html>
	);
}
