import './globals.scss';
import { Inter } from 'next/font/google';
import Providers from './hooks/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<main className='flex flex-col min-h-screen py-2 px-5 md:py-5 md:px-12 xl:py-10 xl:px-24'>
					<Providers>{children}</Providers>
				</main>
			</body>
		</html>
	);
}
